Allow long options

diff --git a/bin/txtnish b/bin/txtnish
--- a/bin/txtnish
+++ b/bin/txtnish
@@ -1022,27 +1022,116 @@ EOF
 # Command line parsing #
 ########################
 
+check_if_valid_option () {
+	case "$options" in
+		*,$1,* ) : ;;
+		* ) usage "Invalid option $OPTION" ;;
+	esac
+}
+
+set_optarg_seperated () {
+	[ -n "$1" ] || usage "Option $OPTION requires an argument."
+	OPTARG="$1"
+}
+
+set_optarg_long_combined () {
+	[ -n "${OPTION#*=}" ] || usage "Option ${OPTION%%=*} requires an argument."
+	OPTARG="${OPTION#*=}"
+}
+
+set_optarg_short_combined () {
+	[ -n "${OPTION#??}" ] || usage "Option ${OPTION%%${OPTION#??}} requires an argument."
+	OPTARG="${OPTION#*??}"
+	
+}
+
 call_mode () {
-	while getopts ":$options" opt; do
-		case $opt in
-			l ) limit="$OPTARG" ;;
-			h ) usage ;;
-			p ) use_pager=1 ;;
-			P ) use_pager=0 ;;
-			u ) always_update=1 ;;
-			U ) always_update=0 ;;
-			a ) sort_order=ascending ;;
-			d ) sort_order=descending ;;
-			N ) max_procs="$OPTARG" ;;
-			S ) filter_expr="$OPTARG" ;;
-			R ) raw_timeline=1 ;;
-			B ) : ;;
-			v ) verbose=1 ;;
-			: ) usage "Option -$OPTARG requires an argument." ;;
-			\? ) usage "Invalid option -$OPTARG." ;;
+	while [ -n "$1" ]; do
+		OPTION=$1
+		case $1 in
+			-l | --limit )
+				check_if_valid_option limit
+				set_optarg_seperated "$2"
+				limit="$OPTARG"
+				shift
+				;;
+			--limit=?* )
+				check_if_valid_option limit
+				set_optarg_long_combined
+				limit="$OPTARG"
+				;;
+			-l?* )
+				check_if_valid_option limit
+				set_optarg_short_combined
+				limit="$OPTARG"
+				;;
+			-h | --help )
+				check_if_valid_option help
+			       	usage
+				;;
+			-p | --pager )
+				check_if_valid_option pager
+				use_pager=1
+				;;
+			-P | --no-pager )
+				check_if_valid_option no-pager
+				use_pager=0
+				;;
+			-u | --update )
+				check_if_valid_option update
+				always_update=1
+				;;
+			-U | --no-update )
+				check_if_valid_option no-update
+				always_update=0
+				;;
+			-a | --ascending )
+				check_if_valid_option ascending
+				sort_order=ascending
+				;;
+			-d | --descending )
+				check_if_valid_option descending
+				sort_order=descending
+				;;
+			-N | --max-procs )
+				check_if_valid_option max-procs
+				set_optarg_seperated "$2"
+				max_procs="$OPTARG"
+				shift
+				;;
+			--max-procs=?* )
+				check_if_valid_option max-procs
+				set_optarg_long_combined
+				max_procs="$OPTARG"
+				;;
+			-N?* )
+				check_if_valid_option max_procs
+				set_optarg_short_combined
+				max_procs="$OPTARG"
+				;;
+			-S | --search )
+				check_if_valid_option search
+				set_optarg_seperated "$2"
+				filter_expr="$OPTARG"
+				shift
+				;;
+			--search=?* )
+				check_if_valid_option search
+				set_optarg_long_combined
+				filter_expr="$OPTARG"
+				;;
+			-R | --raw )
+				check_if_valid_option raw
+				raw_timeline=1
+				;;
+			-v | --verbose )
+				check_if_valid_option verbose
+				verbose=1
+				;;
+			-* ) usage "Invalid option $1." ;;
 		esac
+		shift
 	done
-	shift $(( OPTIND - 1 ))
 
 	case $mode in
 		*-* ) mode="${mode%-*}_${mode#*-}"
@@ -1098,23 +1187,24 @@ usage () {
 		Options:
 EOF
 
+	options="$options,"
 	while [ -n "$options" ] ;do
-		c=${options%${options#?}}
+		c=${options%%,*}
 		case $c in
-			h ) printf "  -h     Print a help message and exit.\n" ;;
-			l ) printf "  -l NUM Limit total numer of tweets shown.\n" ;;
-			a ) printf "  -a     Sort timeline in ascending order.\n" ;;
-			d ) printf "  -d     Sort timeline in descending order.\n" ;;
-			p ) printf "  -p     Use pager to display content.\n" ;;
-			P ) printf "  -P     Do not use pager to display content.\n" ;;
-			u ) printf "  -u     Update sources.\n" ;;
-			U ) printf "  -U     Do not update sources.\n" ;;
-			R ) printf "  -R     Print raw timeline.\n" ;;
-			N ) printf "  -N NUM Use NUM parallel download processes.\n" ;;
-			S ) printf "  -S EXP Filter tweets\n" ;;
-			c ) printf "  -c CFG Specify a custom config file location.\n" ;;
+			help )       printf "  -h, --help\n\tPrint a help message and exit.\n" ;;
+			limit )      printf "  -l, --limit\n\t NUM Limit total numer of tweets shown.\n" ;;
+			ascending )  printf "  -a, --ascending\n\tSort timeline in ascending order.\n" ;;
+			descending ) printf "  -d, --descending\n\tSort timeline in descending order.\n" ;;
+			pager )      printf "  -p, --pager\n\tUse pager to display content.\n" ;;
+			no-pager )   printf "  -P, --no-pager\n\tDo not use pager to display content.\n" ;;
+			update )     printf "  -u, --update\n\tUpdate sources.\n" ;;
+			no-update )  printf "  -U, --no-update\n\tDo not update sources.\n" ;;
+			raw )        printf "  -R, --raw\n\tPrint raw timeline.\n" ;;
+			max-procs )  printf "  -N, --max-procs NUM\n\tUse NUM parallel download processes.\n" ;;
+			search )     printf "  -S, --search EXP\n\tFilter tweets\n" ;;
+			config )     printf "  -c, --config CFG\n\tSpecify a custom config file location.\n" ;;
 		esac
-		options=${options#?}
+		options=${options#$c,}
 	done
 
 	## Always end usage with a empty line
@@ -1147,19 +1237,35 @@ if ! have_cmd curl;then
 	die "curl has to be installed."
 fi
 
-while getopts ":c:hv" opt;do
-	case $opt in
-		V ) printf "%s\n" "$VERSION"; exit 0  ;;
-		h ) usage_main ;;
-		c )
-			config_file="$OPTARG"
-			if ! [ -e "$config_file" ];then
-				die "Missing configuration file '$config_file'";
-			fi
+# while getopts ":c:hv" opt;do
+while [ -n "$1" ]; do
+	case $1 in
+		-v | --version )
+			printf "%s\n" "$VERSION"
+			exit 0
 			;;
-		: ) usage_main "Option -$OPTARG requires an argument." ;;
-		\? ) usage_main "Invalid option -$OPTARG." ;;
+		-h | --help )
+			usage_main
+			;;
+		-c | --config )
+			[ -n "$2" ] || die "Option $1 requires an argument."
+			config_file="$2"
+			[ -e "$config_file" ] || die "Missing configuration file '$config_file'";
+			shift
+			;;
+		--config=?* )
+			config_file="${1#*=}"
+			[ -n "$config_file" ] || die "Option ${1%%=*} requires an argument."
+			[ -e "$config_file" ] || die "Missing configuration file '$config_file'";
+			;;
+		-* )
+			die "Invalid option $1"
+			;;
+		* )
+			break
+			;;
 	esac
+	shift
 done
 
 shift $(( OPTIND - 1))
@@ -1178,57 +1284,57 @@ shift
 case $mode in
 	update )
 		synopsis="Fetching new twtfiles from all your sources."
-		options="hN:v"
+		options="help,verbose,max-procs"
 		;;
 	follow )
 		synopsis="Add a new source to your followings."
 		arguments="NICK SOURCE"
-		options="hv"
+		options="help,verbose"
 		;;
 	unfollow )
 		synopsis="Remove an existing source from your followings."
 		arguments="NICK"
-		options="hv"
+		options="help,verbose"
 		;;
 	following )
 		synopsis="Return the list of sources you're following."
-		options="hv"
+		options="help,verbose"
 		;;
 	timeline | view )
 		synopsis="Display timeline."
 		arguments="[NICK...]"
-		options="hl:adpPuUN:S:Rv"
+		options="help,limit,verbose,ascending,descending,update,no-update,max-procs,search,pager,no-pager,raw"
 		;;
 	reply )
 		synopsis="Reply to tweets."
 		arguments="[NICK]"
-		options="hl:aduUN:S:v"
+		options="help,limit,verbose,ascending,descending,update,no-update,max-procs,search"
 		;;
 	publish )
 		synopsis="Publish your twtfile."
-		options="hv"
+		options="help,verbose"
 		;;
 	tweet )
 		synopsis="Append a new tweet to your twtxt file."
 		arguments="[TWEET...]"
-		options="hv"
+		options="help,verbose"
 		;;
 	sync-followings )
 		synopsis="Sync followings from a remote file."
-		options="hv"
+		options="help,verbose"
 		;;
 	mail )
 		synopsis="Mail new tweets."
 		arguments="ADDRESS ..."
-		options="hvaduU:"
+		options="help,verbose,ascending,descending,update,no-update"
 		;;
 	mailpipe )
 		synopsis="Read mails from stdin and tweet them."
-		options="hv"
+		options="help,verbose"
 		;;
 	quickstart )
 		synopsis="Import settings from twtxt."
-		options="hv"
+		options="help,verbose"
 		;;
 	* ) printf "Unknown mode %s.\n" "$mode" >&2; usage_main; exit 1;;
 
