Read config before options are parsed

diff --git a/bin/txtnish b/bin/txtnish
--- a/bin/txtnish
+++ b/bin/txtnish
@@ -500,7 +500,7 @@ publish () {
 ########################
 
 call_mode () {
-	while getopts ":$options" opt;do
+	while getopts ":$options" opt; do
 		case $opt in
 			l ) limit="$OPTARG" ;;
 			h ) usage ;;
@@ -512,19 +512,12 @@ call_mode () {
 			d ) sort_order=descending ;;
 			N ) max_procs="$OPTARG" ;;
 			S ) filter_expr="$OPTARG" ;;
-			c )
-				config_file="$OPTARG"
-				if ! [ -e "$config_file" ];then
-					die "Missing configuration file '$config_file'";
-				fi
-				;;
 			B ) http_backend="$OPTARG" ;;
 			: ) usage "Option -$OPTARG requires an argument." ;;
 			\? ) usage "Invalid option -$OPTARG." ;;
 		esac
 	done
 	shift $(( OPTIND - 1 ))
-	read_config
 	$mode "$@"
 }
 
@@ -617,16 +610,24 @@ if ! have_cmd curl && have_cmd wget;then
 	http_backend=wget
 fi
 
-while getopts ":hvc:B:" opt;do
+while getopts ":c:hv" opt;do
 	case $opt in
 		v ) printf "$VERSION\n"; exit 0  ;;
 		h ) usage_main ;;
+		c )
+			config_file="$OPTARG"
+			if ! [ -e "$config_file" ];then
+				die "Missing configuration file '$config_file'";
+			fi
+			;;
 		: ) usage_main "Option -$OPTARG requires an argument." ;;
 		\? ) usage_main "Invalid option -$OPTARG." ;;
 	esac
 done
 
 shift $(($OPTIND - 1))
+
+read_config
 
 mode=$1
 
@@ -640,47 +641,47 @@ shift
 case $mode in
 	update )
 		synopsis="Fetching new twtfiles from all your sources."
-		options="chN:B:"
+		options="hN:B:"
 		call_mode "$@"
 		;;
 	follow )
 		synopsis="Add a new source to your followings."
 		arguments="NICK SOURCE"
-		options="ch"
+		options="h"
 		call_mode "$@"
 		;;
 	unfollow )
 		synopsis="Remove an existing source from your followings."
 		arguments="NICK"
-		options="ch"
+		options="h"
 		call_mode "$@"
 		;;
 	following )
 		synopsis="Return the list of sources you're following."
-		options="ch"
+		options="h"
 		call_mode "$@"
 		;;
 	timeline | view )
 		synopsis="Display timeline."
 		arguments="[NICK...]"
-		options="chl:adpPuUN:S:B:"
+		options="hl:adpPuUN:S:B:"
 		call_mode "$@"
 		;;
 	reply )
 		synopsis="Reply to tweets."
 		arguments="[NICK]"
-		options="chl:aduUN:S:B:"
+		options="hl:aduUN:S:B:"
 		call_mode "$@"
 		;;
 	publish )
 		synopsis="Publish your twtfile."
-		options="ch"
+		options="h"
 		call_mode "$@"
 		;;
 	tweet )
 		synopsis="Append a new tweet to your twtxt file."
 		arguments="[TWEET...]"
-		options="ch"
+		options="h"
 		call_mode "$@"
 		;;
 	* ) printf "Unknown mode $mode.\n" >&2; usage_main; exit 1;;
