Add pre_tweet_hook and sync_twtfile (fixes #5)

diff --git a/bin/txtnish b/bin/txtnish
--- a/bin/txtnish
+++ b/bin/txtnish
@@ -535,6 +535,7 @@ expand_mentions () {
 
 draft_to_twtfile () {
 	[ -s "$draft_file" ] || return
+	pre_tweet_hook
 	_fracsecs=0
 	_timestamp_fmt=$(TZ=C date "+%Y-%m-%dT%H:%M:%S.%%06iZ")
 	while read -r msg;do
@@ -558,6 +559,20 @@ draft_to_twtfile () {
 cleanup () {
 	[ -e "$tempfile" ] && rm "$tempfile"
 	[ -d "$tempdir" ] && rm -r "$tempdir"
+}
+
+sync_twtfile () {
+	if [ -n "$twtfile" ] && [ -n "$twturl" ]; then
+		if ! curl -sS -o "$twtfile" "$twturl"; then
+			die "Can't sync twtfile. Aborting."
+		fi
+	else
+		die "Set twtfile and twturl to sync twtfile. Aborting.\n"
+	fi
+}
+
+pre_tweet_hook () {
+	:
 }
 
 post_tweet_hook () {
