Wrap code in main()

diff --git a/bin/txtnish b/bin/txtnish
--- a/bin/txtnish
+++ b/bin/txtnish
@@ -1206,128 +1206,132 @@ EOF
 ## Main #
 #########
 
-trap cleanup EXIT
+main() {
 
-create_dir "$config_dir"
-create_dir "$cache_dir"
-create_dir "$cache_dir/twtfiles"
-create_dir "$cache_dir/timestamps"
-create_dir "$log_dir"
+	trap cleanup EXIT
 
-if ! [ -e "$follow_file" ];then
-	:> "$follow_file"
-fi
+	create_dir "$config_dir"
+	create_dir "$cache_dir"
+	create_dir "$cache_dir/twtfiles"
+	create_dir "$cache_dir/timestamps"
+	create_dir "$log_dir"
 
-if ! have_cmd curl;then
-	die "curl has to be installed."
-fi
+	if ! [ -e "$follow_file" ];then
+		:> "$follow_file"
+	fi
 
-# while getopts ":c:hv" opt;do
-while [ -n "$1" ]; do
-	SHIFT=1
-	OPTION="$1"
-	case $1 in
-		-v | --version )
-			printf "%s\n" "$VERSION"
-			exit 0
+	if ! have_cmd curl;then
+		die "curl has to be installed."
+	fi
+
+	while [ -n "$1" ]; do
+		SHIFT=1
+		OPTION="$1"
+		case $1 in
+			-v | --version )
+				printf "%s\n" "$VERSION"
+				exit 0
+				;;
+			-h | --help )
+				usage_main
+				;;
+			-c | --config | --config=?* | -c?*  )
+				set_optarg "$@"
+				config_file="$OPTARG"
+				[ -e "$config_file" ] || die "Missing configuration file '$config_file'";
+				;;
+			-??* )
+				shift
+				## dash 0.5.7 can't handle direct expansion
+				_tmp=${OPTION#??}
+				set -- "${OPTION%$_tmp}" "-$_tmp" "$@"
+				SHIFT=0
+				;;
+			-* )
+				usage "Invalid option $1"
+				;;
+			* )
+				break
+				;;
+		esac
+		shift "$SHIFT"
+	done
+
+	shift $(( OPTIND - 1))
+
+	read_config
+
+	mode=$1
+
+	if [ -z "$mode" ];then
+		usage_main
+		exit 1
+	fi
+
+	shift
+
+	case $mode in
+		update )
+			synopsis="Fetching new twtfiles from all your sources."
+			options="help,verbose,max-procs"
 			;;
-		-h | --help )
-			usage_main
+		follow )
+			synopsis="Add a new source to your followings."
+			arguments="NICK SOURCE"
+			options="help,verbose"
 			;;
-		-c | --config | --config=?* | -c?*  )
-			set_optarg "$@"
-			config_file="$OPTARG"
-			[ -e "$config_file" ] || die "Missing configuration file '$config_file'";
+		unfollow )
+			synopsis="Remove an existing source from your followings."
+			arguments="NICK"
+			options="help,verbose"
 			;;
-		-??* )
-			shift
-			## dash 0.5.7 can't handle direct expansion
-			_tmp=${OPTION#??}
-			set -- "${OPTION%$_tmp}" "-$_tmp" "$@"
-			SHIFT=0
+		following )
+			synopsis="Return the list of sources you're following."
+			options="help,verbose"
 			;;
-		-* )
-			die "Invalid option $1"
+		timeline | view )
+			synopsis="Display timeline."
+			arguments="[NICK...]"
+			options="help,limit,verbose,ascending,descending,update,no-update,max-procs,search,pager,no-pager,raw"
 			;;
-		* )
-			break
+		reply )
+			synopsis="Reply to tweets."
+			arguments="[NICK]"
+			options="help,limit,verbose,ascending,descending,update,no-update,max-procs,search"
 			;;
+		publish )
+			synopsis="Publish your twtfile."
+			options="help,verbose"
+			;;
+		tweet )
+			synopsis="Append a new tweet to your twtxt file."
+			arguments="[TWEET...]"
+			options="help,verbose"
+			;;
+		sync-followings )
+			synopsis="Sync followings from a remote file."
+			options="help,verbose"
+			;;
+		mail )
+			synopsis="Mail new tweets."
+			arguments="ADDRESS ..."
+			options="help,verbose,ascending,descending,update,no-update"
+			;;
+		mailpipe )
+			synopsis="Read mails from stdin and tweet them."
+			options="help,verbose"
+			;;
+		quickstart )
+			synopsis="Import settings from twtxt."
+			options="help,verbose"
+			;;
+		* ) printf "Unknown mode %s.\n" "$mode" >&2; usage_main; exit 1;;
+
 	esac
-	shift "$SHIFT"
-done
 
-shift $(( OPTIND - 1))
+	call_mode "$@"
 
-read_config
+	exit 0
+}
 
-mode=$1
-
-if [ -z "$mode" ];then
-	usage_main
-	exit 1
-fi
-
-shift
-
-case $mode in
-	update )
-		synopsis="Fetching new twtfiles from all your sources."
-		options="help,verbose,max-procs"
-		;;
-	follow )
-		synopsis="Add a new source to your followings."
-		arguments="NICK SOURCE"
-		options="help,verbose"
-		;;
-	unfollow )
-		synopsis="Remove an existing source from your followings."
-		arguments="NICK"
-		options="help,verbose"
-		;;
-	following )
-		synopsis="Return the list of sources you're following."
-		options="help,verbose"
-		;;
-	timeline | view )
-		synopsis="Display timeline."
-		arguments="[NICK...]"
-		options="help,limit,verbose,ascending,descending,update,no-update,max-procs,search,pager,no-pager,raw"
-		;;
-	reply )
-		synopsis="Reply to tweets."
-		arguments="[NICK]"
-		options="help,limit,verbose,ascending,descending,update,no-update,max-procs,search"
-		;;
-	publish )
-		synopsis="Publish your twtfile."
-		options="help,verbose"
-		;;
-	tweet )
-		synopsis="Append a new tweet to your twtxt file."
-		arguments="[TWEET...]"
-		options="help,verbose"
-		;;
-	sync-followings )
-		synopsis="Sync followings from a remote file."
-		options="help,verbose"
-		;;
-	mail )
-		synopsis="Mail new tweets."
-		arguments="ADDRESS ..."
-		options="help,verbose,ascending,descending,update,no-update"
-		;;
-	mailpipe )
-		synopsis="Read mails from stdin and tweet them."
-		options="help,verbose"
-		;;
-	quickstart )
-		synopsis="Import settings from twtxt."
-		options="help,verbose"
-		;;
-	* ) printf "Unknown mode %s.\n" "$mode" >&2; usage_main; exit 1;;
-
-esac
-
-call_mode "$@"
-
-exit 0
+main "$@"
